import { FactCheckClaim, Source } from "@civiclens/types";

export const FACT_CHECK_SOURCES: Source[] = [
  {
    id: "src-pib-factcheck",
    name: "Press Information Bureau (PIB) Fact Check Unit",
    publisher: "Ministry of Information and Broadcasting, Government of India",
    url: "https://factcheck.pib.gov.in",
    publicationDate: "2024-08-15",
    sourceType: "PIB_RELEASE",
    isOfficial: true,
  },
  {
    id: "src-rbi-circulars",
    name: "Reserve Bank of India (RBI) Official Clarification Desk",
    publisher: "Reserve Bank of India (RBI)",
    url: "https://rbi.org.in/scripts/BS_PressReleaseDisplay.aspx",
    publicationDate: "2024-07-20",
    sourceType: "GOVERNMENT_REPORT",
    isOfficial: true,
  },
  {
    id: "src-eci-press",
    name: "Election Commission of India (ECI) Clarifications",
    publisher: "Election Commission of India",
    url: "https://eci.gov.in/press-releases",
    publicationDate: "2024-06-01",
    sourceType: "ECI_AFFIDAVIT",
    isOfficial: true,
  },
  {
    id: "src-cag-clarification",
    name: "Comptroller and Auditor General (CAG) Media Cell",
    publisher: "Office of the Comptroller & Auditor General of India",
    url: "https://cag.gov.in",
    publicationDate: "2024-05-12",
    sourceType: "CAG_AUDIT",
    isOfficial: true,
  },
  {
    id: "src-sci-registry",
    name: "Supreme Court of India Official Orders & Judgments",
    publisher: "Supreme Court of India",
    url: "https://main.sci.gov.in",
    publicationDate: "2024-04-26",
    sourceType: "GOVERNMENT_REPORT",
    isOfficial: true,
  },
  {
    id: "src-npc-upi",
    name: "National Payments Corporation of India (NPCI) Official Notice",
    publisher: "NPCI Circulars",
    url: "https://www.npci.org.in",
    publicationDate: "2024-03-30",
    sourceType: "INDEPENDENT_RESEARCH",
    isOfficial: true,
  },
];

export const FACT_CHECK_CLAIMS: FactCheckClaim[] = [
  {
    id: "fc-upi-18-percent-gst",
    title: "18% GST Imposed on All UPI Transactions Above ₹2,000",
    claim: "Government of India has announced an 18% GST surcharge on all peer-to-peer (P2P) and person-to-merchant (P2M) UPI payments above ₹2,000 starting from next month.",
    claimant: "Viral WhatsApp Forward & Social Media Image Cards",
    verdict: "FALSE",
    truthSummary: "No GST is levied on ordinary citizen UPI payments. Person-to-Person (P2P) and normal merchant payments remain 100% free with zero surcharge.",
    debunkExplanation: "National Payments Corporation of India (NPCI) and Ministry of Finance clarified that standard bank-to-bank UPI transfers are completely free for citizens. The 1.1% interchange fee applies strictly to Prepaid Payment Instruments (wallets like Paytm wallet) for high-value merchant transactions, paid by the merchant—not normal bank UPI users.",
    category: "ECONOMY",
    viralityScore: 94,
    confidenceScore: 99,
    dateReported: "2024-08-10",
    highlightedRedFlags: ["18% GST on UPI", "Forward to all family members", "charges start tomorrow", "hidden tax on GPay"],
    officialClarificationUrl: "https://pib.gov.in/PressReleasePage.aspx?PRID=1911425",
    officialSourceLabel: "Ministry of Finance & PIB Fact Check",
    evidenceId: "ev-upi-gst-debunk",
    suggestedAction: "Do not circulate. UPI transactions from regular bank accounts remain zero-fee for consumers.",
  },
  {
    id: "fc-free-pm-recharge-scheme",
    title: "Govt Providing Free ₹5,000 Mobile Recharge Under PM Yojna",
    claim: "Prime Minister Narendra Modi is providing a free 3-month ₹5,000 mobile recharge to all Indian youths for the upcoming elections. Click bit.ly/pm-recharge-free to claim before 31st.",
    claimant: "WhatsApp Viral Phishing Messages & Telegram Channels",
    verdict: "FALSE",
    truthSummary: "Government has launched no such free recharge scheme. The viral link is a phishing / malware trap designed to steal personal data and OTPs.",
    debunkExplanation: "PIB Fact Check and Ministry of Electronics & IT confirmed that the Government of India does not run any scheme offering free mobile recharges or telecom vouchers. Official government websites end only in .gov.in or .nic.in; suspicious bit.ly or .xyz domains are malicious cyber fraud links.",
    category: "SCHEMES",
    viralityScore: 98,
    confidenceScore: 100,
    dateReported: "2024-08-01",
    highlightedRedFlags: ["bit.ly/pm-recharge", "Click before 31st", "Free ₹5,000 recharge", "Forward to 10 friends"],
    officialClarificationUrl: "https://twitter.com/PIBFactCheck/status/178129034",
    officialSourceLabel: "PIB Fact Check Bureau",
    evidenceId: "ev-pm-recharge-fake",
    suggestedAction: "Never click suspicious short links or share bank OTPs. Report phishing numbers to 1930 (Cyber Crime Helpline).",
  },
  {
    id: "fc-cag-7-point-5-lakh-cr-scam",
    title: "CAG Found ₹7.5 Lakh Crore Scam in Ayushman Bharat PM-JAY",
    claim: "Comptroller and Auditor General (CAG) report exposed a massive ₹7.5 Lakh Crore scam where millions of treatments were billed on a single fake mobile number 9999999999.",
    claimant: "Viral Opposition & Social Media Claims",
    verdict: "MISLEADING",
    truthSummary: "The total budgetary allocation for Ayushman Bharat since inception is under ₹40,000 Cr. The CAG detected database entry validation errors (dummy phone numbers in BIS 1.0), not a ₹7.5 Lakh Crore embezzlement.",
    debunkExplanation: "Audit Report No. 11 of 2023 of the CAG evaluated performance audits of PM-JAY. CAG highlighted systemic software flaws in the Beneficiary Identification System (BIS 1.0) where operators filled '9999999999' when patients lacked phones. The total hospital claims reimbursed across all years combined were ~₹11,200 Cr, making a ₹7.5 Lakh Cr financial theft physically impossible. Ministry of Health updated BIS to Aadhaar OTP verification.",
    category: "CAG_CORRUPTION",
    viralityScore: 91,
    confidenceScore: 96,
    dateReported: "2024-07-28",
    highlightedRedFlags: ["₹7.5 Lakh Crore stolen", "CAG confirmed largest scam", "all hospitals siphoned money"],
    officialClarificationUrl: "https://cag.gov.in/en/audit-report/details/115462",
    officialSourceLabel: "CAG Audit Report No. 11 & Parliamentary Disclosures",
    evidenceId: "ev-cag-pmjay-analysis",
    suggestedAction: "Refer to official CAG audit report paragraphs for audited reconciliation rather than exaggerated viral graphics.",
  },
  {
    id: "fc-rbi-green-strip-500-note",
    title: "RBI Declared ₹500 Notes With Green Strip Near Gandhi Picture Invalid",
    claim: "Reserve Bank of India circular claims ₹500 notes where the green security thread is close to Mahatma Gandhi's photo instead of Governor's signature are fake and invalid from today.",
    claimant: "Viral WhatsApp Audio Note & Infographic",
    verdict: "FALSE",
    truthSummary: "Both varieties of ₹500 banknotes are 100% genuine legal tender. Slight printing displacement during high-speed RBI press minting does not make notes counterfeit.",
    debunkExplanation: "The Reserve Bank of India has repeatedly issued public notifications stating that minor alignment variations in the position of the security thread occur during the intaglio printing process and both types are valid legal tender. No ₹500 notes have been demonetized or banned.",
    category: "ECONOMY",
    viralityScore: 89,
    confidenceScore: 100,
    dateReported: "2024-06-18",
    highlightedRedFlags: ["Green strip near Gandhi photo", "Bank will not accept", "Declare fake today", "Audio from bank manager"],
    officialClarificationUrl: "https://www.rbi.org.in/scripts/BS_PressReleaseDisplay.aspx",
    officialSourceLabel: "Reserve Bank of India Press Release",
    evidenceId: "ev-rbi-currency-debunk",
    suggestedAction: "Both notes are legal tender. Banks cannot refuse deposit or exchange.",
  },
  {
    id: "fc-sc-ban-evm-paper-ballot",
    title: "Supreme Court Banned EVMs & Ordered Paper Ballots for All Elections",
    claim: "Supreme Court 5-Judge Constitution Bench passed a landmark verdict banning Electronic Voting Machines (EVMs) and ordering 100% paper ballot voting in India.",
    claimant: "Viral YouTube Videos & Facebook Posts",
    verdict: "FALSE",
    truthSummary: "Supreme Court upheld EVM integrity and rejected 100% VVPAT paper slip counting in its landmark April 26, 2024 verdict (ADR v. ECI).",
    debunkExplanation: "A two-judge bench of Justices Sanjiv Khanna and Dipankar Datta rejected the plea for returning to paper ballots, ruling that EVMs are secure, robust, and prevent booth capturing. The court instead ordered administrative measures like sealing symbol loading units (SLUs) post-polling.",
    category: "ELECTIONS",
    viralityScore: 92,
    confidenceScore: 100,
    dateReported: "2024-05-15",
    highlightedRedFlags: ["Supreme Court banned EVM", "Paper ballot returned", "Huge victory for democracy", "Breaking SC Order"],
    officialClarificationUrl: "https://main.sci.gov.in/supremecourt/2023/11824/11824_2023_1_1501_52458_Judgement_26-Apr-2024.pdf",
    officialSourceLabel: "Supreme Court Judgment ADR v. Union of India",
    evidenceId: "ev-sc-evm-verdict",
    suggestedAction: "Check official Supreme Court judgment registry rather than misleading sensational YouTube thumbnails.",
  },
  {
    id: "fc-free-pm-solar-chulha",
    title: "Free Indian Oil Solar Chulha under PM Free Stove Scheme",
    claim: "Central Government offering 100% free Surya Nutan Solar Cookstove to all Indian women with Aadhaar card. Apply on pmfreesolarchulha.online before quota exhausts.",
    claimant: "Viral Forward with Phishing Website Link",
    verdict: "FALSE",
    truthSummary: "No free solar chulha DBT scheme exists. Surya Nutan is a commercial cookstove developed by Indian Oil, sold through authorized IndianOil distributors with no free government portal.",
    debunkExplanation: "Indian Oil Corporation Limited (IOCL) and Ministry of Petroleum clarified that Surya Nutan is available through authorized commercial distributor channels and there is no government portal named 'pmfreesolarchulha.online'. The fraudulent portal was created to harvest banking details and registration fees.",
    category: "SCHEMES",
    viralityScore: 86,
    confidenceScore: 98,
    dateReported: "2024-07-05",
    highlightedRedFlags: ["pmfreesolarchulha.online", "Quota expiring", "Free solar stove", "Pay ₹199 processing fee"],
    officialClarificationUrl: "https://twitter.com/PIBFactCheck/status/171420194",
    officialSourceLabel: "PIB Fact Check & IndianOil Statement",
    evidenceId: "ev-solar-chulha-fake",
    suggestedAction: "Never pay registration fees on unverified third-party websites claiming to be government portals.",
  },
  {
    id: "fc-who-emergency-lockdown-india",
    title: "WHO Declared National Emergency in India With Impending Lockdowns",
    claim: "World Health Organization (WHO) issued a red alert notice for India instructing immediate school closures and national emergency protocols starting Friday midnight.",
    claimant: "Viral WhatsApp Forward with WHO logo image",
    verdict: "FALSE",
    truthSummary: "WHO has issued no such emergency notice or lockdown advisory for India. Public health indicators remain under routine national surveillance.",
    debunkExplanation: "WHO India country office and Union Ministry of Health & Family Welfare confirmed that the viral circular using a forged WHO letterhead is completely fake. No travel restrictions or school closures have been mandated.",
    category: "HEALTH",
    viralityScore: 88,
    confidenceScore: 100,
    dateReported: "2024-06-25",
    highlightedRedFlags: ["Midnight lockdown", "WHO Red Alert India", "Forward to all parents", "Emergency protocol active"],
    officialClarificationUrl: "https://www.who.int/india/news",
    officialSourceLabel: "World Health Organization (WHO) India & MoHFW",
    evidenceId: "ev-who-health-debunk",
    suggestedAction: "Follow only official MoHFW (mohfw.gov.in) updates for healthcare advisories.",
  },
  {
    id: "fc-aadhaar-voter-cancellation",
    title: "Voting Rights Cancelled If Aadhaar Card Not Linked by This Week",
    claim: "Election Commission of India will strike names off the national electoral roll if voters do not link Aadhaar with Voter ID (EPIC) on NVSP portal before end of the month.",
    claimant: "Viral Social Media Posts & Messages",
    verdict: "FALSE",
    truthSummary: "Linking Aadhaar with Voter ID is 100% voluntary under Section 23(5) of the Representation of the People Act. No voter can be deleted for not providing Aadhaar.",
    debunkExplanation: "ECI made an official submission before the Supreme Court affirming that Form 6B (Aadhaar submission) is strictly voluntary. Non-furnishing of Aadhaar is not a ground for striking any citizen's name off the electoral roll.",
    category: "ELECTIONS",
    viralityScore: 85,
    confidenceScore: 100,
    dateReported: "2024-04-18",
    highlightedRedFlags: ["Name deleted from voter list", "Mandatory Aadhaar linking", "Vote cancelled", "Urgent deadline"],
    officialClarificationUrl: "https://eci.gov.in/files/file/14352-voluntary-submission-of-aadhaar-number/",
    officialSourceLabel: "Election Commission of India Notification",
    evidenceId: "ev-eci-aadhaar-clarification",
    suggestedAction: "Check your active voting status on voters.eci.gov.in using your EPIC number.",
  },
  {
    id: "fc-traffic-fine-hard-copy-rc",
    title: "₹25,000 Traffic Fine for Showing Digilocker / mParivahan RC & DL",
    claim: "Traffic police across states have stopped accepting DigiLocker documents; showing soft copies of Driving License and RC on phone will attract ₹25,000 challan and vehicle seizure.",
    claimant: "Viral Instagram Reels & WhatsApp Audio",
    verdict: "FALSE",
    truthSummary: "DigiLocker and mParivahan electronic documents are legally valid and binding on all traffic police under Rule 139 of the Central Motor Vehicles Rules (CMVR).",
    debunkExplanation: "Ministry of Road Transport and Highways (MoRTH) circular clearly establishes that digital documents presented via DigiLocker or mParivahan mobile applications have equal legal validity to physical documents and traffic police cannot penalize motorists for not carrying original paper cards.",
    category: "LEGAL",
    viralityScore: 82,
    confidenceScore: 100,
    dateReported: "2024-05-30",
    highlightedRedFlags: ["₹25,000 challan for DigiLocker", "Hard copy mandatory", "Traffic police banned phone RC"],
    officialClarificationUrl: "https://morth.nic.in/central-motor-vehicles-rules-1989",
    officialSourceLabel: "Ministry of Road Transport & Highways (MoRTH) Circular",
    evidenceId: "ev-morth-digilocker-rule",
    suggestedAction: "Ensure your documents are pulled directly from the official DigiLocker or mParivahan app (not plain photos/screenshots).",
  },
  {
    id: "fc-pm-kisan-16th-installment-scam",
    title: "PM-KISAN 16th Installment Increased to ₹12,000 Yearly for All",
    claim: "Cabinet has officially doubled PM-KISAN payouts from ₹6,000 to ₹12,000 per year for all landholding farmers starting immediately. Register bank account on kisan-bonus.in.",
    claimant: "Phishing SMS & Unverified YouTube Videos",
    verdict: "MISLEADING",
    truthSummary: "Union Budget 2024-25 retains PM-KISAN at ₹6,000 annually in 3 installments of ₹2,000. Certain state supplements exist (like Maharashtra Namo Shetkari ₹6,000), but Central PM-KISAN remains ₹6,000.",
    debunkExplanation: "Ministry of Agriculture & Farmers Welfare confirmed that no national hike to ₹12,000 has been notified by the Union Cabinet. Some states provide state-funded top-ups, but fraudulent links asking for bank details to 'unlock' ₹12,000 are phishing scams.",
    category: "SCHEMES",
    viralityScore: 90,
    confidenceScore: 97,
    dateReported: "2024-07-15",
    highlightedRedFlags: ["kisan-bonus.in", "₹12,000 double payout", "Click link to receive money", "Cabinet secret approval"],
    officialClarificationUrl: "https://pmkisan.gov.in",
    officialSourceLabel: "Ministry of Agriculture & PM-KISAN Portal",
    evidenceId: "ev-pm-kisan-outlays",
    suggestedAction: "Only use pmkisan.gov.in. Never enter bank PIN or OTP on unverified .in or .org websites.",
  }
];

export const VIRAL_PATTERNS_DB = [
  {
    trigger: ["free recharge", "free mobile", "jio recharge", "airtel recharge", "5000 recharge", "recharge yojna"],
    verdict: "FALSE" as const,
    truthSummary: "Government does not provide free telecom recharges. This is a known phishing mechanism.",
    category: "SCHEMES" as const,
  },
  {
    trigger: ["18% gst on upi", "gst on upi", "upi charges above 2000", "gpay tax", "phonepe tax"],
    verdict: "FALSE" as const,
    truthSummary: "Normal citizen bank-to-bank UPI transfers remain 100% free with 0% GST.",
    category: "ECONOMY" as const,
  },
  {
    trigger: ["green strip", "500 note fake", "gandhi photo note", "rbi banned 500"],
    verdict: "FALSE" as const,
    truthSummary: "Both variations of the ₹500 banknote are genuine legal tender recognized by RBI.",
    category: "ECONOMY" as const,
  },
  {
    trigger: ["supreme court banned evm", "sc banned evm", "ballot paper return", "paper ballot order"],
    verdict: "FALSE" as const,
    truthSummary: "Supreme Court rejected petitions to return to paper ballots in April 2024 judgment.",
    category: "ELECTIONS" as const,
  },
  {
    trigger: ["7.5 lakh crore", "7.5 lakh cr cag", "ayushman scam 7.5 lakh", "9999999999 cag"],
    verdict: "MISLEADING" as const,
    truthSummary: "Total Ayushman budget is under ₹40,000 Cr; CAG flagged software phone-number entry flaws, not ₹7.5L Cr theft.",
    category: "CAG_CORRUPTION" as const,
  },
  {
    trigger: ["free solar chulha", "free solar stove", "pm solar chulha", "pmfreesolarchulha"],
    verdict: "FALSE" as const,
    truthSummary: "No free solar cookstove DBT scheme exists; Surya Nutan is a commercial IOCL product.",
    category: "SCHEMES" as const,
  },
  {
    trigger: ["who emergency", "national emergency lockdown", "lockdown from friday", "who red alert"],
    verdict: "FALSE" as const,
    truthSummary: "WHO has issued no lockdown advisory or emergency alert for India.",
    category: "HEALTH" as const,
  },
  {
    trigger: ["digilocker fine", "25000 traffic fine", "hard copy rc mandatory", "digilocker banned"],
    verdict: "FALSE" as const,
    truthSummary: "DigiLocker and mParivahan digital vehicular documents are legally binding under CMVR Rule 139.",
    category: "LEGAL" as const,
  },
  {
    trigger: ["aadhaar voter cancel", "vote cancelled aadhaar", "name deleted voter list"],
    verdict: "FALSE" as const,
    truthSummary: "Aadhaar-Voter ID linking is voluntary; no citizen's name can be struck off for not linking Aadhaar.",
    category: "ELECTIONS" as const,
  },
];
